default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5

development:
    <<: *default
    database: webtech_group_development

test:
    <<: *default
    database: webtech_group_test

production:
    <<: *default
    database: webtech_group_production
    username: webtech_group
    password: <%= ENV['WEBTECH_GROUP_DATABASE_PASSWORD'] %>
